# The Docker image that will be used to build your app
image: nixos/nix
# Functions that should be executed before the build script is run
before_script:
  - echo "trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=" >> /etc/nix/nix.conf
  - echo "substituters = https://cache.garnix.io?priority=41 https://cache.nixos.org/" >> /etc/nix/nix.conf
  - echo "experimental-features = nix-command" >> /etc/nix/nix.conf

pages:
  script:
    - nix build -o ./public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
