# zk configuration file

# NOTE SETTINGS
[note]
language = "en"
filename = "{{slug title}}"
extension = "md"

template = "topics.md"

# The default title used for new note, if no `--title` flag is provided.
default-title = "untitled"

# MARKDOWN SETTINGS
[format.markdown]
link-format = "[[{{filename}}]]"
hashtags = true
colon-tags = false
multiword-tags = false

# EXTERNAL TOOLS
[tool]
editor = "nvim"
pager = "bat"

# fzf-preview = "bat -p {-1}"
fzf-preview = "zk list --quiet --format full --limit 1 {-1}"

# LSP
[lsp.diagnostics]
# Each diagnostic can have for value: none, hint, info, warning, error
wiki-title = "hint"
dead-link = "error"

# COMMAND ALIASES
[alias]
# create new lecture or topic note for current course
lecture = "zk new --title (echo \"Lecture\" (date +%Y-%m-%d)) --template \"lecture.md\" $UNI_COURSE_NOTES_DIR/Lectures"
lec-edit = "zk edit $UNI_COURSE_NOTES_DIR/Lectures --interactive"
topic = "zk edit $UNI_COURSE_NOTES_DIR/Topics --interactive"

# edit config
conf = '$EDITOR "$UNI_NOTES_DIR/.zk/config.toml"'
