name: "CI"

on:
  push:
    branches:
      - "main"

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: publish site
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://cache.garnix.io?priority=41 https://cache.nixos.org/

      - name: build
        run: |
          nix build -o ./_site
          if ! [ -f ./_site/index.html ]; then
            echo "ERROR: There is no index.html"
            exit 2
          fi

      - name: cloudflare action
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: baefa62f242180429d549bebf70158fa
          projectName: Uni Notes
          directory: ./_site
