name: Dispatch notes update to dependent repos

on:
  push:
    branches:
      - main

jobs:
  notify-site:
    runs-on: ubuntu-latest
    steps:
      - name: Send dispatch to site repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.SUBMODULE_SSH_KEY }}
          repository: vaisriv/uni.vaisriv.com
          event-type: notes-updated
          client-payload: |
            {
              "notes_sha": "${{ github.sha }}",
              "notes_branch": "${{ github.ref_name }}"
            }
      - name: Send dispatch to uni repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.SUBMODULE_SSH_KEY }}
          repository: vaisriv/uni
          event-type: notes-updated
          client-payload: |
            {
              "notes_sha": "${{ github.sha }}",
              "notes_branch": "${{ github.ref_name }}"
            }
